Figaro.require_keys("RESET_MAIL_VALIDITY_HOURS", "VERIFY_MAIL_VALIDITY_HOURS",
                    "REMEMBER_ME_COOKIE_EXPIRY_DAYS", "DEFAULT_FROM_MAIL", "PER_PAGE_DEAL",
                    "HOSTNAME")